### ISSUE TITLE
ApiException 

### ISSUE THREAD

**Issue by Jericho** [Pathoschild/FluentHttpClient#13]
This is more a question that an issue: did you design FluentClient to purposefully throw an exception whenever the HttpResponse is anything other than HTTP200?

The reason I ask is that with the standard HttpClient I would receive a response, check the StatusCode and decide what to do. For example, if the status code is 429 (which means 'TOO MANY REQUESTS') I have code to automatically pause and reissue the request. With FluentClient I think my logic will have to be different: I think I need to `try ... catch` the call `var response = await _fluentClient.SendAsync(httpRequest);` and check the status code in the `catch` block.

Also, can you think of a better design? For instance, is there a way to write a IFilter that would check the statuscode in the 'OnResponse' and reissue the request if necessary?

**Comment by Jericho** [comment]
I found a workaround that works well for me:

```
try 
{
    var response = await _fluentClient.SendAsync(httpRequest);
    return await response.AsMessage();
}
catch (ApiException apiEx)
{
    return apiEx.ResponseMessage;
}
```

**Comment by Pathoschild** [comment]
That behaviour is from the `DefaultErrorFilter`, which is just an `IFilter` that throws when it receives a non-success code. It's easy to [replace the filter or remove it outright](https://github.com/Pathoschild/FluentHttpClient#error-handling), in which case it won't throw an exception anymore.

In theory you could auto-retry with an `IFilter`, but it would be messy with the current implementation (since you can _change_ the response, but you can't _replace_ it). We could certainly change the interface to support that scenario if needed (in a backwards-compatible way).
