### ISSUE TITLE
Review design decisions

### ISSUE THREAD

**Issue by Pathoschild** [Pathoschild/FluentHttpClient#36]
The next version will be 3.0 since we have breaking changes as part of #22 and #31. Since we're already incrementing the major version, review the design decisions taken in earlier versions in case there are other breaking changes we should consider.

## To do
* [x] `AsList<T>()` should return `T[]` instead of `List<T>`.
* [x] `AsList<T>()` should be named `AsArray<T>()`.
* [x] Eliminate obsolete `JsonNetFormatter`.
* [x] Simplify `IHttpFilter` by removing message arguments (already available via `IRequest` and `IResponse`).

**Comment by Pathoschild** [comment]
To consider:
- `AsList<T>()` should return `T[]` instead of `List<T>` (suggested by @Jericho).
- The client throws exceptions by default for non-success responses. Should we rethink the default error-handling logic?

**Comment by Jericho** [comment]
Originally I was strongly in favor of removing the default error handling for at least two reasons:

- when I started using the FluentHttpClient package I was not aware that this behavior was overidable(I guess I didn't pay attention to the 'Error Handling' section in the ReadMe!)
- I was trying to write my own retry logic to handle HTTP 429 "Too many requests" but the default error handling was interfering because it would throw an exception before I could handle the response. Therefore my code was full of `try ... catch`.

However, since we recently added built-in retry logic to FluentHttpClient which automatically retries requests before the error handler processes the response, I no longer have such a strong opinion. I'm fine with keeping the default error handler, especially since I now know that I can remove it and replace it with my own error handling if desired.

**Comment by Jericho** [comment]
Another breaking change to consider:

- Getting rid of the obsolete `JsonNetFormatter`.

**Comment by Jericho** [comment]
Regarding `AsList`, I propose not only changing the returned type but also changing the name of the method to `AsArray`.

**Comment by Pathoschild** [comment]
I removed `JsonNetFormatter` and changed `response.AsList<T>()` to return an array.

I'm not sure about renaming `AsList` though; the name refers to a conceptual list of resources, not the data structure that represents it. I'm not necessarily opposed to renaming it, though. What do you think?

**Comment by Pathoschild** [comment]
The current error-handling behaviour can be counterintuitive. For example, consider the following code:

```cs
IResponse response = await client.GetAsync(…);
if (response.StatusCode != HttpStatusCode.OK)
  …
```

If the response code isn't `HttpStatusCode.OK`, the `if` check will never be reached since an exception will be thrown instead. The only way around that would be to remove the `ErrorFilter` from the client before making the request. I'm not sure what the best way to handle that would be yet, though.

**Comment by Jericho** [comment]
**Re AsList**: personally I would find it confusing if the method name contained 'List' but it returned an array.

**Re Error handling**: what you just described is exactly what I experienced when I started using FluentHttpClient and I had to change all my code which was checking the status code of the response with try ... catch. I didn't realize that the error handling filter could be removed until you told me. People who are transitioning from using the .net HttpClient to this client are used to checking the status code therefore I think it would be preferable not to register the error handling filter. You could leave the class in the project which would allow developers to use it if they like it.

**Comment by Pathoschild** [comment]
Fair enough, I renamed `AsList<T>()` to `AsArray<T>()`.

**Comment by Pathoschild** [comment]
I split the error-handling discussion to #38.

**Comment by Jericho** [comment]
Two additional breaking changes to consider:
- The `OnRequest` method on the `IHttpFilter` interface accepts a `IRequest` and a `HttpRequestMessage` parameters. This is not necessary since `IRequest` has a read-only `Message` property.
- The `OnResponse` method on the `IHttpFilter` interface accepts a `IResponse` and a `HttpResponseMessage` parameters. This is not necessary since `IResponse` has a read-only `Message` property.

Therefore I suggest changing the `IHttpFilter` interface like so:
```CSharp
   public interface IHttpFilter
    {
        /// <summary>Method invoked just before the HTTP request is submitted. This method can modify the outgoing HTTP request.</summary>
        /// <param name="request">The HTTP request.</param>
        void OnRequest(IRequest request);

        /// <summary>Method invoked just after the HTTP response is received. This method can modify the incoming HTTP response.</summary>
        /// <param name="response">The HTTP response.</param>
        void OnResponse(IResponse response);
    }
```
For example, the `DefaultErrorFilter` would be modified like so:
```CSharp
    public class DefaultErrorFilter : IHttpFilter
    {
        /*********
        ** Public methods
        *********/
        /// <summary>Method invoked just before the HTTP request is submitted. This method can modify the outgoing HTTP request.</summary>
        /// <param name="request">The HTTP request.</param>
        public void OnRequest(IRequest request) { }

        /// <summary>Method invoked just after the HTTP response is received. This method can modify the incoming HTTP response.</summary>
        /// <param name="response">The HTTP response.</param>
        public void OnResponse(IResponse response)
        {
            if (!response.Message.IsSuccessStatusCode)
                throw new ApiException(response, $"The API query failed with status code {response.Message.StatusCode}: {response.Message.ReasonPhrase}");
        }
    }
```

**Comment by Pathoschild** [comment]
Makes sense to me. Done in `develop`. :)

**Comment by Pathoschild** [comment]
I'll close this since the proposed changes are done, but feel free to reopen if anything else comes up before 3.0 releases.
