### ISSUE TITLE
Downgrade System.Net.Http 

### ISSUE THREAD

**Issue by Jericho** [Pathoschild/FluentHttpClient#41]
The NETFULL (i.e. .net 4.5.2) target of my library currently references the System.Net.Http nuget package which I intend to replace with FluentHttpClient as soon as the next release with "retries" is publicly available. A user recently opened a [ticket](https://github.com/Jericho/StrongGrid/issues/109) to complain that he can't use my library because System.Net.Http 4.0.0 requires a version of the nuget client that is not available in Visual Studio 2013 (he says he is in a corporate environment and can't upgrade to VS.NET 2015). The solution is to downgrade System.Net.Http to 2.0.20710 which works for him and since other users are free to use a more recent version if they desire, this solution seems to satisfy all my users. I was not able to find release notes so I don't know specifically what's different but my (somewhat) educated guess is that supporting NETSTANDARD and unsealing classes for easier unit testing are the major changes. So far I haven't noticed any other significant change between 2.x and 4.x

However, this solution will go out the window when I start referencing FluentHttpClient because it's NETFULL target references System.Net.Http 4.0.0. So my question is: what do you think about downgrading the reference to 2.0.20710?

**Comment by Pathoschild** [comment]
I'd rather not depend on such an old version because NuGet [automatically installs the lowest compatible version of the dependency](https://docs.microsoft.com/en-us/nuget/consume-packages/dependency-resolution#dependency-resolution-rules). That means new projects would automatically get one of the earliest versions of HttpClient, with none of the bugfixes and improvements since 2012.

How about putting a custom downgraded version of the client on your MyGet feed instead?

**Comment by Jericho** [comment]
Yea, that's probably what I'll end up doing. To be honest with you, I don't even have access to VS 2013, so I can't even do any kind of testing so I don't really want to support it, at least not "officially".
