### ISSUE TITLE
Migrate content negotiation to .NET Standard

### ISSUE THREAD

**Issue by ghost** [Pathoschild/FluentHttpClient#68]
Added Pathoschild.Http.FluentClient to an ASP .NET Core 2.0 WebAPI project.

Called PostAsync and received:

System.Resources.MissingManifestResourceException: 'Could not find any resources appropriate for the specified culture or the neutral culture.  Make sure "System.Net.Http.Properties.Resources.resources" was correctly embedded or linked into assembly "WinInsider.System.Net.Http.Formatting" at compile time, or that all the satellite assemblies required are loadable and fully signed.'

Packages installed:

    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.0" />
    <PackageReference Include="Pathoschild.Http.FluentClient" Version="3.0.0" />

**Comment by Jericho** [comment]
This is a [known issue](https://github.com/Pathoschild/FluentHttpClient/issues/52#issuecomment-279179890) that I mentioned a few months ago. The issue is that some problem occurred and in the process of throwing the exception, some code in a nuget package tries to get the error message from an external assembly but this assembly is missing. In other words: an error occurred while trying to throw the exception about the underlying problem.

What's frustrating is that this problem with the missing assembly is hiding the details about the underlying issue and therefore it makes it hard for you to pinpoint what the issue is.

**Comment by Pathoschild** [comment]
That's a flaw in the `WinInsider.System.Net.Http.Formatting` library as Jericho mentions, which we're using because `MediaTypeFormatter` (from `System.Net.Http.Formatting`) isn't available in .NET Standard yet. With .NET Standard 2.0 released, we should look into whether we can replace it with a .NET Standard equivalent for content negotiation.

**Comment by Pathoschild** [comment]
[Microsoft.AspNet.WebApi.Client 5.2.4 alpha](https://www.myget.org/feed/aspnetwebstacknightly/package/nuget/Microsoft.AspNet.WebApi.Client) adds the missing APIs for .NET Standard 1.1, but the last release was in February. Based on discussion in aspnet/Mvc#5822, the release timeline isn't clear.

**Comment by ghost** [comment]
Looks like we can have a resolution in future. Luckily, there's plenty to be getting on with and I can return to this at when fixed. Thanks.

**Comment by Pathoschild** [comment]
Still waiting for Microsoft.AspNet.WebApi.Client 5.2.4, no timeline available (that isn't already past).

**Comment by Pathoschild** [comment]
WebApi client 5.2.4 is finally released and includes `MediaTypeFormatter`, so we can drop the third-party workaround. However, we'll need to target .NET Standard 2.0 instead of 1.3, losing compatibility with some older versions:

|.NET Standard              | [1.3] |      [2.0] |
|:------------------------- |-----: |----------: |
|.NET Core                  |  1.0  |        2.0 |
|.NET Framework             |  4.6  |      4.6.1 |
|Mono                       |  4.6  |        5.4 |
|Xamarin.iOS                | 10.0  |      10.14 |
|Xamarin.Mac                |  3.0  |        3.8 |
|Xamarin.Android            |  7.0  |        8.0 |
|Universal Windows Platform | 10.0  | 10.0.16299 |

[1.3]: https://github.com/dotnet/standard/blob/master/docs/versions/netstandard1.3.md
[2.0]: https://github.com/dotnet/standard/blob/master/docs/versions/netstandard2.0.md

Any objections? (@Jericho?)

**Comment by Jericho** [comment]
Losing compatibility with .netstandard1.x is a big deal for me. My library targets net452 and netstandard1.3 so if you change your target to netstandard2.0 I won’t be able to use your new version. Maybe you could multi-target 1.3 and 2.0 and conditionally reference the appropriate nuget package depending on the target? I know this wouldn’t achieve your goal of completely getting rid of the 3rd party package but it would be a first step.

**Comment by Pathoschild** [comment]
Yeah, I thought of that later. Multitargeting is easy, so there's no need to reduce compatibility. We can also target Framework 4.5 instead of 4.5.2. So we'll support:

target | dependencies
------ | ------------
.NET Framework 4.5 | [Microsoft.AspNet.WebApi.Client](https://www.nuget.org/packages/Microsoft.AspNet.WebApi.Client) 5.2.4
.NET Standard 2.0 | [Microsoft.AspNet.WebApi.Client](https://www.nuget.org/packages/Microsoft.AspNet.WebApi.Client) 5.2.4
.NET Standard 1.3 | [Newtonsoft.Json](https://www.nuget.org/packages/Newtonsoft.Json) 10.0.3<br />[System.Net.Http](https://www.nuget.org/packages/System.Net.Http) 4.3.0<br />[WinInsider.System.Net.Http.Formatting](https://www.nuget.org/packages/WinInsider.System.Net.Http.Formatting) 1.0.5

**Comment by Jericho** [comment]
I know that you _can_ target net4.5 but why? Microsoft [stopped supporting it in January 2016](https://support.microsoft.com/en-us/help/17455/lifecycle-faq-net-framework).

**Comment by Pathoschild** [comment]
We don't need any changes to support 4.5, since our dependencies are already compatible, so why not? It won't affect anyone using 4.5.2+.

**Comment by Pathoschild** [comment]
Done in `develop` for the upcoming 3.2 release. (Feel free to comment if you disagree with supporting .NET Framework 4.5.)
