### ISSUE TITLE
don't want to put you on the spot ... but can you compare this to flurl ... trying to pick one

### ISSUE THREAD

**Issue by aktxyz** [Pathoschild/FluentHttpClient#92]

**Comment by Pathoschild** [comment]
They have similar capabilities and both will work fine in the vast majority of cases, so it mostly comes down to which API you like better.

Here are some notable differences to help you decide. (I tried to be fair in the comparison, but of course I'm more familiar with FluentHttpClient. Feel free to ask the Flurl author for their perspective too.)

## Notable differences
### API design and discoverability
* Flurl adds a _lot_ of extensions on `string` and adds every method to one big list. That can be messy since they'll appear on all strings and be mixed in with other string methods. Note the scrollbar:
  > ![](https://user-images.githubusercontent.com/230581/80313191-6c106480-87b7-11ea-92ae-28830cad09c2.png)

* FluentHttpClient uses a fluent builder API, so you see the most relevant methods at each step. That makes it much easier to use without having to refer to documentation. For example, create a client and start a request:
  > ![](https://user-images.githubusercontent.com/230581/80313455-fd340b00-87b8-11ea-870b-aa0b5e81fcee.png)

  Then configure the request:
  > ![](https://user-images.githubusercontent.com/230581/80313512-471cf100-87b9-11ea-9e79-8802d15c1af1.png)

  Then handle the response:
  > ![](https://user-images.githubusercontent.com/230581/80313544-759acc00-87b9-11ea-9fb6-d8112de768b5.png)

### High-level APIs
* Flurl tends to be lower-level, so it doesn't handle some of the common stuff for you. For example, it has no default `User-Agent` header (required for many APIs) and you can't easily reuse request options (e.g. authentication to use across multiple requests to an API).

* FluentHttpClient tends to be higher-level, and handles some common things for you. It adds a `User-Agent` header by default (easily overridden), you can set common request options on the client, it has built-in authentication/formatting helpers, etc.

### Serialization
* Flurl uses a custom `ISerializer` interface for its serialization, so you're limited to the ones created specifically for Flurl (or which you create yourself).
* FluentHttpClient uses the .NET Framework's `MediaTypeFormatter`, so [there are thousands available](https://www.nuget.org/packages?q=MediaTypeFormatter) in addition to the ones built-in. If you create your own web API, you can use the same `MediaTypeFormatter` on both ends.

### Retry policies
* Flurl doesn't support retry policies. They suggest using a library like [Polly](https://github.com/App-vNext/Polly) to wrap each request with retry logic.
* FluentHttpClient has built-in support for retry policies, which you can define per-client or per-request. For advanced cases you can also create a 'request coordinator' for fully custom retry (or other coordination) logic, use it with a library like Polly, etc.

### Extensibility
* Flurl provides some [events for extensibility](https://flurl.dev/docs/configuration/) (roughly equivalent to FluentHttpClient's filters) and lets you override the underlying `HttpClient` and `HttpMessageHandler`.
* FluentHttpClient lets you extend pretty much everything &mdash; custom formats, custom error-handling, add logic before/after requests, add request coordinators (e.g. for custom retry logic), override the underlying `HttpClient` and `HttpMessageHandler`, and customise individual requests.

## Usage comparison
Let's say you're calling a pretty standard REST API. It needs a user agent header and API key, and you need to call two endpoints. Here's how you'd do it with each client.

### Flurl
```cs
// create a user agent string (not handled by Flurl)
string userAgent = $"YourClient/1.0.0 ({RuntimeInformation.OSDescription?.Trim()}; {RuntimeInformation.OSArchitecture}; {RuntimeInformation.FrameworkDescription})";

// fetch a news story
NewsStory story = await "https://example.org/api"
   .AppendPathSegment("news")
   .SetQueryParam("id", 15)
   .WithHeader("Authentication", "ApiKey ...")
   .WithHeader("User-Agent", userAgent)
   .GetJsonAsync<NewsStory>();

// fetch comments
Comment[] comments = await "https://example.org/api"
   .AppendPathSegment($"news/{story.id}/comments")
   .SetQueryParams(new { page = 1, pageSize = 50 })
   .WithHeader("Authentication", "ApiKey ...")
   .WithHeader("User-Agent", userAgent)
   .GetJsonAsync<Comment[]>();
```

### FluentHttpClient
```cs
// create client with the common request settings (user agent added automatically)
var client = new FluentClient("https://example.org/api")
   .SetAuthentication("ApiKey", "...");

// fetch a news story
NewsStory story = await client
   .GetAsync("news")
   .WithArgument("id", 15)
   .As<NewsStory>();

// fetch comments
Comment[] comments = await client
   .GetAsync($"news/{story.id}/comments")
   .WithArguments(new { page = 1, pageSize = 50 })
   .As<Comment[]>();
```
