### ISSUE TITLE
fluentclient constructor breaks from 3.2.0 to 4.0.0

### ISSUE THREAD

**Issue by zqfan** [Pathoschild/FluentHttpClient#94]
https://github.com/Pathoschild/FluentHttpClient/blob/3.2/Client/FluentClient.cs#L57

why this public method is removed?
```
        /// <summary>Construct an instance.</summary>
        /// <param name="baseUri">The base URI prepended to relative request URIs.</param>
        /// <param name="proxy">The web proxy.</param>
        public FluentClient(string baseUri, IWebProxy proxy)
            : this(new Uri(baseUri), proxy) { }
```
it seems no harm to inherit in 4.0.0, but it do break the compatibility, for advanced information please refer to this issue https://github.com/TencentCloud/tencentcloud-sdk-dotnet/issues/34

**Comment by Pathoschild** [comment]
FluentHttpClient 4.0 simplifies the constructors to make usage more intuitive (e.g. it adds a default constructor and removes multiple `string` vs `Uri` overloads). The equivalent for that one is `FluentClient(Uri baseUri, IWebProxy proxy)`.

Since 4.0 is a major release with breaking changes, unfortunately you can't use it interchangeably with 3.2. I suggest either updating the SDK to use 4.0, or locking the package to 3.2 as z2665 mentioned on that issue. Feel free to ask if you need any help updating!
